---
title: "Data Visualization"
date: "`r weekdays(Sys.Date())`, `r as.numeric(format(Sys.Date(),'%d'))`^`r ifelse(as.numeric(format(Sys.Date(), '%d')) %in% c(1,21,31),'st',ifelse(as.numeric(format(Sys.Date(), '%d')) %in% c(2,22),'nd',ifelse(as.numeric(format(Sys.Date(), '%d')) %in% c(3,23),'rd','th')))`^ `r format(Sys.Date(),'%B %Y')`"
output: html_document
---

## Introduction

```{r}
knitr::opts_chunk$set(fig.align = 'center',
                      echo = F)

library(data.table)
library(geojsonio)
library(ggplot2)
library(viridis)
library(duckdb)
library(plotly)
library(arrow)
library(broom)
library(sp)

source("../src/spatial_library.R")
source("../src/key_amazon.R")
```

```{r}
# Create duckdb connection
duckdb_con = DBI::dbConnect(duckdb::duckdb())

DT = open_dataset("s3://envbran/WQ/WQ_underground.arrow",format = "arrow") 
DT = DT |> to_duckdb(table_name = "test", 
                     con = duckdb_con)

WC = DT |>
  filter(anno == "2019") |>
  as.data.table() 

WC[, lat := unlist(WC$lat)]
WC[, lng := unlist(WC$lng)]

WC = map_point(district, WC, "district_id")
WC[, valore_numerico := as.numeric(gsub(",",".",valore_numerico))]
WC = WC[parametro == "Solfati"]
WC = WC[,.(valore_numerico = mean(valore_numerico,na.rm = T)), by = district_id]
WC[, district_id := as.numeric(as.character(district_id))]
```


```{r, message=FALSE}
# Health district 
district =  geojson_read("https://www.dati.lombardia.it/resource/9n45-7bpc.geojson",
                         what = "sp")
dt_district = tidy(district)
dt_district = data.table(dt_district)
dt_district = merge(dt_district,
                    district@data[,c("objectid_1","codice_ats","distretto","descrizion")],
                    by.x = "id", by.y = "objectid_1")
dt_district$id = as.numeric(dt_district$id)
dt_district = merge(dt_district,WC, by.x = "id", by.y = "district_id")

```

```{r, fig.height=6, fig.width=8}
map_lomb = ggplot() +
  geom_polygon(data = dt_district, aes(x = long, y = lat, 
                                          group = group, fill = valore_numerico), 
               color="white") +
  theme_void() +
  scale_fill_viridis() +
  coord_map() + 
  labs(title = "Solfati ground water 2019",
       subtitle = "unit measure: mg/L",
       caption = "data: ArpaLombardia 2019") +
  theme(plot.title = element_text(hjust = 0.5,size = 18),
        plot.subtitle = element_text(hjust = 0.5,size = 15),
        legend.position="none") 
  
ggplotly(map_lomb)
```

